# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4499f6c53c97041e2da55b6056c59b7f90ffd9271a0d0753de75af36ec766da9eed3e89a993796504363647854eb92cbb2b4348688d3051cd4c0d68b9ed933c4

test:
  secret_key_base: 5c458dc54836c4bb8e32aafc31a5ca1a17d64ef97b601a0bf3d96b146fcdda4b741ea2b055e447644696982fec4e1561f5629966236a6307006e6579b946fe64

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
